POST http://localhost:8080/distance
Content-Type: application/json

{
  "first_pos": {"x": 0, "y": 0},
  "second_pos": {"x": 1, "y": 2}
}
###
GET http://localhost:8080/robots

###
PUT http://localhost:8080/robot/1/position
Content-Type: application/json

{
  "position": {"x": 3, "y": 4}
}

###
PUT http://localhost:8080/robot/1/position
Content-Type: application/json

{
  "position": {"x": 5, "y": 6}
}

###
POST http://localhost:8080/distance
Content-Type: application/json

{
  "first_pos": "robot#1", "second_pos": {"x": 0, "y": 8}
}

###
POST http://localhost:8080/nearest
Content-Type: application/json

{
  "ref_position": {"x": -1, "y": 1}
}

###
POST http://localhost:8080/distance
Content-Type: application/json

{
  "first_pos": {"x": 3, "y": -2},
  "second_pos": {"x": -1, "y": 1},
  "metric": "manhattan"
}

###
POST http://localhost:8080/distance
Content-Type: application/json

{
  "first_pos": {"x": 3, "y": -2},
  "second_pos": {"x": -1, "y": 1},
  "metric": "euclidean"
}