POST http://localhost:8080/distance
Content-Type: application/json

{
  "first_pos": {"x": 3, "y": -2},
  "second_pos": {"x": -1, "y": 1}
}
###
GET http://localhost:8080/robots

###
POST http://localhost:8080/tweets
Content-Type: application/json

{
  "username": "darmmykung",
  "content": "เบื่อจังเลย"
}

###
POST http://localhost:8080/tweets
Content-Type: application/json

{
  "username": "ptongkung",
  "content": "ทำไมน้องไม่ยกมือกันเลย"
}
###
GET http://localhost:8080/tweets
###
PUT http://localhost:8080/tweets/1
Content-Type: application/json

{
  "username": "darmmykung",
  "content": "ไม่ชอบวิชานี้เลยว่ะ"
}
###
DELETE http://localhost:8080/tweets/1
